on:
  push:
    branches: [main, ci-cd]
jobs:
  runUnitTests:
    name: Unit Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [10, 12, 14, 16, 18, "latest"]
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Use NodeJS ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: npm
      - name: Install Dependencies
        run: npm install
      - name: Run Unit Tests
        run: npm t utils && npm t custom-error
