name: Run Tests
on:
  push:
    branches: [main, ci-cd]
jobs:
  runUnitTests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [12] #, 14, 16, 18, "latest"
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Use NodeJS ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: npm
      - name: Install Dependencies
        run: npm install
      - name: Run Unit Tests
        run: npm t utils && npm t custom-error
  runE2ETests:
    name: Run E2E Tests
    needs: runUnitTests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [12] #, 14, 16, 18, "latest"
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Use NodeJS ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: npm
      - name: Install Dependencies
        run: npm install
      - name: Setup Postgres
        uses: harmon758/postgresql-action@v1
        with:
          postgresql version: '14'
          postgresql db: 'nc_games_test'
          postgresql user: 'test_user'
          postgresql password: 'secret_password'
      - name: Run E2E tests
        run: PGDATABASE=nc_games_test PGUSER=test_user PGPASSWORD=secret_password npm t app
