on:
  push:
    branches:
      - ci-cd
jobs:
  runUnitTests:
    name: Unit Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [8.1.0, 10, 12, 14, 16, 18]
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          check-latest: true
      - name: Install Dependencies
        run: npm install
      - name: Run Unit Tests
        run: npm t utils
        run: npm t custom-error
