name: Run Tests
on:
  push:
    branches: [main, ci-cd]
  pull_request:
    branches: [main]
jobs:
  runUnitTests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["latest"]
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Use NodeJS ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: npm
      - name: Install Dependencies
        run: npm install
      - name: Run Unit Tests
        run: npm t utils && npm t custom-error
  runE2ETests:
    name: Run E2E Tests
    needs: runUnitTests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["latest"]
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Use NodeJS ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: npm
      - name: Install Dependencies
        run: npm install
      - name: Setup Postgres
        uses: harmon758/postgresql-action@v1
        with:
          postgresql version: '10'
          postgresql db: ${{ secrets.DB_TEST }}
          postgresql user: 'test_user'
          postgresql password: 'secret_password'
      - name: Run E2E tests
        env:
          DB_TEST: ${{ secrets.DB_TEST }}
        run: PGDATABASE=$DB_TEST PGUSER=test_user PGPASSWORD=secret_password npm t app
